name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'

    - name: Build binaries
      run: |
        mkdir dist
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dist/gotter
        GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o dist/gotter.exe
        GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o dist/gotter-darwin

    - name: Create GitHub Release and upload binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/gotter
          dist/gotter.exe
          dist/gotter-darwin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
